version: '3.8'

services:
  app:
    build: ./app-dev
    image: ghcr.io/mll11/python-docker-dev
    restart: always
    ports:
      - 10001:10001 # port for remote debugging
    volumes:
      # Mount local source directory to its container path for applying code changes.
      - ./app-dev/src:/python-docker
    command: flask run --host 0.0.0.0
    environment:
      - FLASK_APP=/python-docker/server.py
      - FLASK_ENV=development # enable debug mode
      - DEBUGGER=true # enable remote debugging
  proxy:
    build: ./proxy
    image: ghcr.io/mll11/python-docker-proxy
    depends_on:
      - app
    restart: always
    ports:
      - 80:80
