version: '3.8'

services:
  app:
    build: ./app
    image: ghcr.io/mll11/python-docker
    restart: always
    networks:
      - backend-network
      - frontend-network
  db:
    image: mysql:8.0.23
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      - MYSQL_DATABASE=flask
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - backend-network
  proxy:
    image: nginx:1.18-alpine
    restart: always
    ports:
      - 80:80
    networks:
      - frontend-network

networks:
  backend-network:
  frontend-network:
